services:
    web:
        container_name: nginx
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
            args:
                - "UID=${UID:-1000}"
                - "GID=${GID:-1000}"
        ports:
            - "${FORWARD_NGINX_PORT:-80}:80"
        volumes:
            - ".:/var/www/html"
        networks:
            - laravel_app
        depends_on:
            - mysql
            - redis

    mysql:
        container_name: mysql
        image: "mysql/mysql-server:8.0"
        restart: unless-stopped
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - "sail-mysql:/var/lib/mysql"
            - "./docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - laravel_app
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
            retries: 3
            timeout: 5s

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - "${FORWARD_PMA_PORT:-8081}:80"
        networks:
            - laravel_app
        depends_on:
            - mysql

    redis:
        container_name: redis
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "sail-redis:/data"
        networks:
            - laravel_app
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    redisinsight:
        container_name: redisinsight
        image: redislabs/redisinsight:latest
        restart: always
        ports:
            - "${FORWARD_REDISINSIGHT_PORT:-8083}:5540"
        networks:
            - laravel_app
        depends_on:
            - redis

    mailhog:
        container_name: mailhog
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "${FORWARD_MAILHOG_PORT:-8082}:8025"
        networks:
            - laravel_app

networks:
    laravel_app:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
